# cloud-config
packages_update: true
packages_upgrade: true
packages:
  - jq
  - iptables-services

runcmd:
  - set -a
  - 'TOKEN=$(curl -x PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")'
  - 'INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .instanceId)'
  - NAT_INTERFACE=$(ip route | grep default | cut -d ' ' -f 5)
  - sysctl -q -w net.ipv4.ip_forward=1
  - sysctl -q -w net.ipv4.conf.$NAT_INTERFACE.send_redirects=0
  - iptables -t nat -A POSTROUTING -o $NAT_INTERFACE -s ${vpc_cidr} -j MASQUERADE
  - aws ec2 modify-instance-attribute --instance-id $INSTANCE_ID --no-source-dest-check
  - aws ec2 associate-address --no-allow-reassociation --instance-id $INSTANCE_ID --allocation-id ${eip_allocation_id}
  - aws ec2 replace-route --route-table-id ${route_table_id} --destination-cidr-block 0.0.0.0/0 --instance-id "$INSTANCE_ID"
  - aws ec2 create-route --route-table-id ${route_table_id} --destination-cidr-block 0.0.0.0/0 --instance-id "$INSTANCE_ID"
bootcmd:
  - set -a
  - NAT_INTERFACE=$(ip route | grep default | cut -d ' ' -f 5)
  - sysctl -q -w net.ipv4.ip_forward=1
  - sysctl -q -w net.ipv4.conf.$NAT_INTERFACE.send_redirects=0
  - iptables -t nat -A POSTROUTING -o $NAT_INTERFACE -s ${vpc_cidr} -j MASQUERADE